version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - logvolume01:/var/log
    depends_on:
      - rabbitmq
      - redis
    links:
      - rabbitmq
      - redis
    command:  sh -c './wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm test'

  redis:
    image: redislabs/rejson:latest
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  logvolume01: {}
  node_modules:
